DROP TABLE Abonnements;
DROP TABLE Préférences; 
DROP TABLE Statut_vidéo; 
DROP TABLE Notifications; 
DROP TABLE Thème;
DROP TABLE Accessibilité; 
DROP TABLE sont_activées;
DROP TABLE Playlist; 
DROP TABLE Statut_playlist; 
DROP TABLE Restreint; 
DROP TABLE Utilisateur; 
DROP TABLE Thématique; 
DROP TABLE Décrit; 
DROP TABLE Commentaire; 
DROP TABLE Suit; 
DROP TABLE Chaine; 
DROP TABLE Possède;
DROP TABLE Détient; 
DROP TABLE Représente; 
DROP TABLE Aime; 
DROP TABLE Vidéo;
DROP TABLE Limite;
DROP TABLE Photo_de_profil;
DROP TABLE Miniature;
DROP TABLE Intéragit; 

CREATE TABLE Abonnements (idAbo INT PRIMARY KEY NOT NULL );
CREATE TABLE Préférences (idPr INT PRIMARY KEY NOT NULL );
CREATE TABLE Statut_vidéo (idStaV INT PRIMARY KEY NOT NULL );
CREATE TABLE Notifications (lvlNotifs varchar(1) CHECK(LIKE '%0%' or '%1%'), idN INT PRIMARY KEY NOT NULL );
CREATE TABLE Thème (nomTh varchar (40) PRIMARY KEY NOT NULL);
CREATE TABLE Accessibilité (taillepolice INT CHECK(Taillepolice between 8 and 36), Contraste INT CHECK(Contraste between -10 and 10), Assisvoc varchar(1) CHECK(LIKE '%Y%' or '%N%'), Sous-titres CLOB, idA INT PRIMARY KEY NOT NULL );
CREATE TABLE sont_activées (idN REFERENCES Notifications, nomTh REFERENCES Thème, idA REFERENCES Accessibilité, PRIMARY KEY(idN, nomTh, idA));
CREATE TABLE Playlist (créadateP default sysdate NOT NULL, Nplaylist varchar(60) NOT NULL, associés default user, idPl INT PRIMARY KEY NOT NULL );
CREATE TABLE Statut_playlist(idStaPl INT PRIMARY KEY NOT NULL );
CREATE TABLE Restreint(idPl REFERENCES Playlist, idStaPl REFERENCES Statut_playlist, Lvlpartage varchar(1) CHECK(LIKE '%0%' or '%1%'), PRIMARY KEY (idPl, idStaPl));
CREATE TABLE Utilisateur (numtel varchar(15), dateN date NOT NULL, nom varchar(30) NOT NULL, prénom varchar(30) NOT NULL, mail varchar(30) CHECK(LIKE '%@%'), idU INT PRIMARY KEY NOT NULL , idPr REFERENCES Préférences, idPl REFERENCES Playlist);
CREATE TABLE Thématique (nomT varchar (255) PRIMARY KEY NOT NULL );
CREATE TABLE Décrit(nomT REFERENCES Thématique, idPl REFERENCES Playlist, PRIMARY KEY (nomT, idPl));
CREATE TABLE Commentaire (contenu varchar(255) NOT NULL, idCo INT PRIMARY KEY NOT NULL , idU REFERENCES Utilisateur);
CREATE TABLE Suit (idU REFERENCES Utilisateur, idAbo REFERENCES Abonnements, PRIMARY KEY (idU, idAbo));
CREATE TABLE Chaine (créadate default sysdate NOT NULL, Nchaine varchar(60) NOT NULL, idCo REFERENCES Commentaire, idCh INT PRIMARY KEY NOT NULL );
CREATE TABLE Possède (idCh REFERENCES Chaine, idAbo REFERENCES Abonnements, PRIMARY KEY (idCh, idAbo));
CREATE TABLE Détient(idCh REFERENCES Chaine, idU REFERENCES Utilisateur, PRIMARY KEY (idCh, idU));
CREATE TABLE Représente (idCh REFERENCES Chaine, nomT varchar(255) REFERENCES Thématique, PRIMARY KEY NOT NULL(idCh, nomT));
CREATE TABLE Aime (likechaine varchar(1) CHECK(LIKE '%Y%' or '%N%') , idCo REFERENCES Commentaire, idCh REFERENCES Chaine, PRIMARY KEY NOT NULL (idCh,idCo));
CREATE TABLE Vidéo (créadateV default sysdate, formatV blob CHECK(LIKE '%.mp4'), durée (TIMESTAMP ('HH:MM:SS')), idV INT PRIMARY KEY NOT NULL , idCo REFERENCES Commentaire, idCh REFERENCES Chaine); 
CREATE TABLE Limite (idStaV REFERENCES Statut_vidéo, idV REFERENCES Vidéo, répertoriée varchar(1) CHECK(LIKE '%Y%' or '%N%'), monétisée varchar(1) CHECK(LIKE '%Y%' or '%N%') , PRIMARY KEY (idStaV,idV));
CREATE TABLE Photo_de_profil(idU REFERENCES Utilisateur ,idCh REFERENCES Chaine, logochaine blob CHECK(LIKE '%.jpg' or '%.png'), logoutilisateur blob CHECK(LIKE '%.jpg' or '%.png'), PRIMARY KEY (idU, idCh));
CREATE TABLE Miniature (formatM blob, extension CHECK(LIKE '%.jpg' or '%.png'), idV REFERENCES Video, PRIMARY KEY(idV));
CREATE TABLE Intéragit(vu varchar(1) CHECK(LIKE '%Y%' or '%N%'), liké varchar(1) CHECK(LIKE '%Y%' or '%N%'), dislike varchar(1) CHECK(LIKE '%Y%' or '%N%'), commente varchar(1) CHECK(LIKE '%Y%' or '%N%') , idV REFERENCES Vidéo, idU REFERENCES Utilisateur, PRIMARY KEY (idV,idU));
COMMIT;